FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/cmd/customer
RUN go build -o /customer-service .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /customer-service .
EXPOSE 9090
CMD ["./customer-service"]
