FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/cmd/shipment
RUN go build -o /shipment-service .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /shipment-service .
COPY --from=builder /app/services/shipment/storage/migrations ./migrations
EXPOSE 8080
CMD ["./shipment-service"]
