static_resources:
  listeners:
  - name: http_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: http
          route_config:
            name: local_route
            virtual_hosts:
            - name: shipment_host
              domains: ["*"]
              routes:
              - match: { prefix: "/api/v1" }
                route:
                  cluster: shipment_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - name: grpc_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 9090 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc
          route_config:
            name: grpc_route
            virtual_hosts:
            - name: customer_host
              domains: ["*"]
              routes:
              - match: { prefix: "/customer.CustomerService/" }
                route:
                  cluster: customer_service
                  timeout: 0s
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: shipment_service
    connect_timeout: 0.25s
    type: logical_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: shipment_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: shipment-service
                port_value: 8080

  - name: customer_service
    connect_timeout: 0.25s
    type: logical_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: customer_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: customer-service
                port_value: 9090
