receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  # Use OTLP exporter to send to Jaeger's OTLP endpoint
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Debug exporter replaces deprecated logging exporter
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, debug]
  
  telemetry:
    logs:
      level: info